server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lyh.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                 #数据库连接池的最小维持连接数
      initial-size: 5             #初始化连接数
      max-total: 5                #最大连接数
      

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      # defaultZone: http://localhost:7001/eureka 单机
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名信息
    prefer-ip-address: true #访问路径可以显示IP地址
    
info:
  app.name: lyh-microservicecloud
  company.name: www.lyh.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT